### ISSUE TITLE
AsyncMysqlQueryResult::mapRows() returns NULL as ""

### ISSUE THREAD

**Issue by lexidor** [slackhq/hack-sql-fake#1]
This line makes all the return values strings, even the NULL values. https://github.com/slackhq/hack-sql-fake/blob/master/src/AsyncMysql/AsyncMysqlQueryResult.php#L42
According to the documentation the return type should be `Vector<Map<string, string>>`, but that seems off. The HHI agrees with that too. However the documentation describes `string|null`.
https://docs.hhvm.com/hack/reference/class/AsyncMysqlQueryResult/mapRows/#examples

Are we sure the return type isn't secretly `Map<string, ?string>`?

**Comment by ssandler** [comment]
You're right! It should be nullable, I am able to get null results back from `mapRows()`.

I'd advise using `mapRowsTyped()` if possible but we should still fix this to match the real behavior despite the HHI

**Comment by lexidor** [comment]
I'll open a bug report on the offending HHI.

**Comment by lexidor** [comment]
The HHI may very soon match the runtime behavior. https://github.com/facebook/hhvm/pull/8540

**Comment by ssandler** [comment]
Thank you for fixing! https://github.com/slackhq/hack-sql-fake/pull/20
