### ISSUE TITLE
Loosen the strict version requirement on HHAST.

### ISSUE THREAD

**Issue by lexidor** [slackhq/hack-sql-fake#15]
Composer.json requires the exact HHAST version `4.0.4` by using an `=4.0.4` version. This blocks the autoload map generation with an exception. If this could be made looser `^4.0.4` the autoload map can be generated again. The typechecker would be happy too.

**Comment by lexidor** [comment]
Maybe hold that off for a bit. In the mean while, I'll use `--no-dev` https://github.com/hhvm/hhast/issues/198

**Comment by ssandler** [comment]
Thank you! I would be happy to loosen the requirements here.

**Comment by ssandler** [comment]
Fixed in ce9c3068594818fc6b356f0ae0f68f59b38e99b4
