### ISSUE TITLE
Question: Is it considered rude to push small commits often causing travis to run many times?

### ISSUE THREAD

**Issue by lexidor** [slackhq/hack-sql-fake#23]
# Issue template for hack-sql-fake

### Please select the options that apply
 - [X] Question

#### Question

QQ: Is it considered rude to push small commits often?
I develop on HHVM4.15 and up. This allows code that typechecks in my version of hh_client, but not on HHVM4.0.4 to go unnoticed until I push. This will cause more Travis jobs (which I assume cost resources to run).

**Comment by ssandler** [comment]
As an open source repository, TravisCI is free. Go forth and commit! Thanks for checking :-)
