### ISSUE TITLE
Question: Are the undocumented formatting modifiers used?

### ISSUE THREAD

**Issue by lexidor** [slackhq/hack-sql-fake#70]
# Issue template for hack-sql-fake

### Please select the options that apply

 - [ ] Feature request
 - [x] Question
 - [ ] Suggestion
 - [ ] Typechecker errors
 - [ ] Incorrect result
 - [ ] Cripplingly bad performance
 - [ ] Crash
 
#### Question

The [queryf implementation](https://github.com/slackhq/hack-sql-fake/blob/main/src/AsyncMysql/QueryFormatter.php) of SQL Fake implements modifiers that are not in Hack's hhi. Do you depend on these extra modifiers?

**Comment by ssandler** [comment]
Hmm no, did they get removed from Hack? Anything hack doesn't have, we should remove.

**Comment by lexidor** [comment]
Collapsed with #71
