### ISSUE TITLE
Alternative for PgSQL?

### ISSUE THREAD

**Issue by andrew-svirin** [slackhq/hack-sql-fake#74]
It is awesome tool, but may be exists something similar for postgresql?

**Comment by ssandler** [comment]
There is not something for postgresql to my knowledge. It would be possible, but not something I plan to work on as we don't use postgresql and I don't have in depth knowledge of its behavior. Would be open to contributions, but it's also worth noting that HHVM itself natively supports MySQL with a well typed async interface, whereas postgresql has a [ported extension](https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext/pgsql) from PHP that isn't well typed and I'm not sure if anyone uses it or not.
